######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 8 16:41:06 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/tapion/projects/Qanetta/. .

# Input
HEADERS += DrawingArea.h MainWindow.h
SOURCES += DrawingArea.cpp main.cpp MainWindow.cpp
