######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 9 11:04:05 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/tapion/projects/Qanetta/. .

# Input
HEADERS += DrawingArea.h MainWindow.h VanettaParser.h
SOURCES += DrawingArea.cpp main.cpp MainWindow.cpp VanettaParser.cpp
