######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 8 14:53:57 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/tapion/projects/Qanetta/. .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
